### ISSUE TITLE
Main layout

### ISSUE THREAD

**Issue by adekro** [adekro/agricola#4]
The layout is composed by:

- A top bar with:
  - a search input field to filter lands by company
  - "Add new farmland" button
- A main body with the list of farmlands that meet the searching criteria
- Data and statistics of the showed/selected lands (to be refined) on the left or right of the page

**Comment by luca1388** [comment]
Connected to issue #3, this ticket could be the result of investigation for a template. Still to be validated

**Comment by luca1388** [comment]
Maybe we can add a side (left?) column with 2 entries: Lands and companies, so when click on lands the list view in the body would display all the registered farmlands, while selecting companies the list would update showing only the list of companies.
Then in the main list with companies or lands, when user clicks on an entry, the detail of that selected item is opened, with a dialog or with a over "layer" like the one used to add a new ticket here.

**Comment by luca1388** [comment]
Example of possible layout:

![Image](https://user-images.githubusercontent.com/20770798/229822868-18e0ecda-d2b8-466c-812a-61d52b1c0319.png)

**Comment by adekro** [comment]
If we select the "fields" item, in side, under the items we put the land statistics filtered from the main list, while if we are dealing with companies, bho... for now, nothing comes to mind.

in any case, under the statistics we can enter some information on the selected record. or if we do not select the record, a layer opens with all the information that we can modify it

i hope you understand me

**Comment by luca1388** [comment]
Si si puo

**Comment by luca1388** [comment]
Yes I like, maybe for companies we can just show nothing, at least for now.

**Comment by luca1388** [comment]
For the selection/opening layers it is something we can decide later and it is not blocking us probably

**Comment by adekro** [comment]
approved Google template! 

good job!
