### ISSUE TITLE
Show farmland data screen

### ISSUE THREAD

**Issue by adekro** [adekro/agricola#6]
Display all the data of a selected farmland (italian "_terreno agricolo_", could be referred also as "field", "land" or "area").
Data could be:

- Type of farming/tilling
- Land registry data (if available)
- Sizes of the field:
  - Area
  - Perimeter
- GPS coordinates
- Owner of the farmland (could be a person or a company)
- Generic textual notes
- Others data to be defined

Data are grouped by year as a kind of historical log because every year the type of farming can change (maybe also the owner)

Note: 1/ 4 a dx (to be refined)

**Comment by luca1388** [comment]
Update: Display on the map component the shape of the current field
