### ISSUE TITLE
Define the product brand

### ISSUE THREAD

**Issue by luca1388** [adekro/agricola#9]
We need to define:

- Colors palette
- Logo
- Text font
- Name of the app (best candidate is _Agricola_)

**Comment by adekro** [comment]
proposed colors 

![Image](https://user-images.githubusercontent.com/33175405/231576039-1df892ce-001b-4685-a349-eedd164fa6d4.png)


  /* Palette Complementari https://color.adobe.com/it/create/color-wheel */
  --color-a:#691F02;
  --color-b:#B53502;
  --color-c:#B54316;
  --color-d:#00B597;
  --color-e:#026957;

    /* Palette Monocromatici https://color.adobe.com/it/create/color-wheel */
    --color-a:#691F02;
    --color-b:#B53604;
    --color-c:#824229;
    --color-d:#B55D3A;
    --color-e:#361001;

the logo of "Aglicoltori del territorio is in a file Logo.js in UI folder", 

font maybe font-family: "Montserrat";
